# Generated by Django 5.0.4 on 2024-05-17 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('email', models.TextField(primary_key=True, serialize=False)),
                ('nome', models.TextField(max_length=255)),
                ('area', models.TextField(max_length=150)),
                ('senha', models.TextField(max_length=100)),
            ],
        ),
    ]
